# Generated by Django 2.1.2 on 2018-10-23 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=30)),
                ('name2', models.CharField(max_length=30)),
                ('name3', models.CharField(max_length=30)),
            ],
        ),
    ]
